### ISSUE TITLE
In Ubuntu 20.04, vvplacy doesn't work!!!

### ISSUE THREAD

**Issue by jimmy940292** [nus-vv-streams/vvtk#21]
Hi, I am a beginner of rust and point cloud. I follow the instructions on github and find some error when executing vvplay
I have installed rust, gcc, g++, cmake, libssl-dev, pkg-config, libfontconfig1-dev

error message:
thread 'main' panicked at 'Failed to focus input context: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }', /home/ccw/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/event_processor.rs:912:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Please help me! Thanks

**Comment by YoungHS-NUS** [comment]
Can you set `RUST_BACKTRACE=1` and run it again? Then we will have more information to check where went wrong, thanks.

**Comment by YoungHS-NUS** [comment]
I will close this issue as there is no more information
