### ISSUE TITLE
`vvplay` camera coordinate is too precise

### ISSUE THREAD

**Issue by weitsang** [nus-vv-streams/vvtk#22]
Should print camera coordinate in 2 decimal places so we don't show something like `4.2413e-0.8`

**Comment by YoungHS-NUS** [comment]
This is supported in new branch feature/vvplay_ui, which will be merged into main upon completion of some other tasks
![image](https://github.com/nus-vv-streams/vvtk/assets/112539360/be23a871-0684-4f82-a00e-8232eb112f05)
