### ISSUE TITLE
Add support for Velodyn's bin file

### ISSUE THREAD

**Issue by weitsang** [nus-vv-streams/vvtk#24]
https://stackoverflow.com/questions/60506331/conversion-of-binary-lidar-data-bin-to-point-cloud-data-pcd-format

**Comment by YoungHS-NUS** [comment]
Is it possible to share a few examples of Velodyn's bin files? I am having troubles finding the suitable datasets

**Comment by YoungHS-NUS** [comment]
vvplay support is added for Velodyne's bin lidar data. we can also convert from bin->ply/pcd. other subcommands are not tested. 
Currently, we only support velodyne's bin file with this format:
(x,y,z,intensity),.......,(x,y,z,intensity)
they should all be float 32 and contains no other information.
