### ISSUE TITLE
Add a new sub-command `info` to query the basic information about volumetric videos

### ISSUE THREAD

**Issue by weitsang** [nus-vv-streams/vvtk#26]
The output should be pairs of key-value pairs, one on each line, using `:` as the separator between keys and values.

### Example 1

```
vv info foo.ply
```
prints if the file is encoded in ASCII or binary format, the number of points, other useful information.
```
format: ply ASCII
num of points: 420014
```
### Example 2
```
vv info ./longdress/ply
```
should output
```
format: ply ASCII
num of frames: 300
average num of points: 529185.4
```
### Example 3
It should support options to display only selected keys.
```
vv info foo.ply --num-of-points 
```

should output
```
420014
```

**Comment by YoungHS-NUS** [comment]
info subcommand is added in `7865c8dc84016dda7dde0f2cd5c01edc945b4eb1`, it has been merged into main branch.
