### ISSUE TITLE
branch-reconstruct, IndexedPointCloud message and PointXyzRgba

### ISSUE THREAD

**Issue by YoHoSo** [nus-vv-streams/vvtk#33]
<img width="1331" alt="image" src="https://github.com/nus-vv-streams/vvtk/assets/112539360/1e2b479e-65eb-418d-a914-027ab401dea2">

maybe it is better to add a new pipeline message enum for your TriangleFace. e.g. 
```rust
IndexedPointCloudWithTriangleFace(PointCloud<PointXyzRgba>, u32, Option<Vec<TriangleFace>>)
```
Since it is not clear yet if TriangleFace will be used elsewhere.
Also, adding a new message enum will not interfere with the original functionality.

Let me know your thoughts on this.

**Comment by YoungHS-NUS** [comment]
<img width="989" alt="image" src="https://github.com/nus-vv-streams/vvtk/assets/112539360/c96b9438-3dc0-47d2-8a3b-dbd56a46536b">
Also for PointXyzRgba, we have talked about this before **over email**. It is better to create a new data structure for the normals. Consider changing into this, and implement the from/to so that PointXyzRgbaWithNormal can convert from/to PointXyzRgba

```rust
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct PointXyzRgbaWithNormal {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub r: u8,
    pub g: u8,
    pub b: u8,
    pub a: u8,
    pub nx: f32,
    pub ny: f32,
    pub nz: f32,
}
```

or alternatively with `Option` for nx, ny, nz.

```rust
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq)]
pub struct PointXyzRgbaWithNormal {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub r: u8,
    pub g: u8,
    pub b: u8,
    pub a: u8,
    pub nx: Option<f32>,
    pub ny: Option<f32>,
    pub nz: Option<f32>,
}
```

Let me know your thoughts

**Comment by YoungHS-NUS** [comment]
Changing the original data structure will generate a lot of incompatibility like this.
<img width="533" alt="image" src="https://github.com/nus-vv-streams/vvtk/assets/112539360/22b174ea-e16a-4936-bb2d-d81638236a9e">

**Comment by bokuanT** [comment]
WeiQiang said he has implemented a more proper class to store points containing normals. I plan on using his new class to replace mine after you have approved his finalised version

**Comment by bokuanT** [comment]
> 

I think this is better than my current implementation, I will do this

**Comment by YoungHS-NUS** [comment]
> WeiQiang said he has implemented a more proper class to store points containing normals. I plan on using his new class to replace mine after you have approved his finalised version

Sure, let's see his idea later
