### ISSUE TITLE
branch-reconstruct, code should follow cargo fmt, and should remove compiler's warnings

### ISSUE THREAD

**Issue by YoHoSo** [nus-vv-streams/vvtk#34]
after development, you should use `cargo fmt` to format your code, and then push your changes.
<img width="1076" alt="image" src="https://github.com/nus-vv-streams/vvtk/assets/112539360/776c4bc0-7e10-4d42-8db0-04c4123bf6c7">

**Comment by YoungHS-NUS** [comment]
In addition to `cargo fmt`, your code should also be free from the compiler's warnings, as we have a workflow in main branch to check for warnings. If your code has compiler warning, the workflow will fail.

<img width="595" alt="image" src="https://github.com/nus-vv-streams/vvtk/assets/112539360/908d5f19-4cb9-4f1b-9388-b64920ef29de">

**Comment by bokuanT** [comment]
Noted, will rectify these issues

**Comment by weitsang** [comment]
Issues fixed and merged into main
